docker pull ghcr.io/koronisk/gribocherv:java_8
docker pull ghcr.io/koronisk/gribocherv:java_11
docker pull ghcr.io/koronisk/gribocherv:java_16
docker pull ghcr.io/koronisk/gribocherv:java_17
docker pull ghcr.io/koronisk/gribocherv:java_18
docker pull ghcr.io/koronisk/gribocherv:java_19
docker pull ghcr.io/koronisk/gribocherv:java_20
docker pull ghcr.io/koronisk/gribocherv:java_21
docker pull ghcr.io/koronisk/gribocherv:java_22
docker pull ghcr.io/koronisk/gribocherv:java_23
docker pull ghcr.io/koronisk/gribocherv:java_24
docker pull ghcr.io/koronisk/gribocherv:java_25
docker pull ghcr.io/koronisk/gribocherv:java_26
docker pull ghcr.io/koronisk/gribocherv:java_27